import type { Metadata } from "next";
import { Quicksand, Merriweather, Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/feature/theme-toggle";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-sans",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "700"],
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${quicksand.variable} ${merriweather.variable} ${firaCode.variable} antialiased bg-background text-foreground`}
      >
        <ThemeProvider>
          {/* Header */}
          <header className="flex items-center justify-end p-4 border-b">
            <ThemeToggle />
          </header>

          {/* Main content */}
          <main className="p-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}